"""User roles enum

Revision ID: e05ec3557e4f
Revises: de4cd4d3037e
Create Date: 2026-10-03 11:20:22.725305

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e05ec3557e4f'
down_revision: Union[str, Sequence[str], None] = 'de4cd4d3037e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'role',
               existing_type=sa.VARCHAR(),
               type_=sa.Enum('spc', 'student', name='role'),
               postgresql_using='lower(role::text)::role',
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'role',
               existing_type=sa.Enum('spc', 'student', name='role'),
               type_=sa.VARCHAR(),
               postgresql_using='role::text',
               nullable=False)
    # ### end Alembic commands ###
